# Generated by Django 3.0.11 on 2021-01-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('html_url', models.URLField()),
                ('git_url', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('disabled', models.BooleanField(default=False)),
                ('stargazers_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.User')),
            ],
        ),
    ]
